name: flutter_guess_game
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  flutter_animation_progress_bar: ^2.0.1

  flutter: 
    sdk: flutter

dev_dependencies: 
  change_app_package_name: ^1.1.0
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/alphabets/
    - assets/images/numbers/